import { suffix } from '..'

describe('accusative case', () => {
  it('simple cases', () => {
    expect(suffix.accusative('ember')).toBe('embert')
  })
  it('words ending with vowels', () => {
    expect(suffix.accusative('kávé')).toBe('kávét')
    expect(suffix.accusative('sárgadinnye')).toBe('sárgadinnyét')
    expect(suffix.accusative('Ede')).toBe('Edét')
    expect(suffix.accusative('apa')).toBe('apát')
    expect(suffix.accusative('pác')).toBe('pácot')
    expect(suffix.accusative('szó')).toBe('szót')
    expect(suffix.accusative('út')).toBe('utat')
    expect(suffix.accusative('nyár')).toBe('nyarat')
    expect(suffix.accusative('állat')).toBe('állatot')
  })
  it('personal pronouns', () => {
    expect(suffix.accusative('én')).toBe('engem')
    expect(suffix.accusative('te')).toBe('téged')
    expect(suffix.accusative('mi')).toBe('minket')
    expect(suffix.accusative('ti')).toBe('titeket')
  })
  it('exceptions tier 1', () => {
    expect(suffix.accusative('cukor')).toBe('cukrot')
    expect(suffix.accusative('szeder')).toBe('szedret')
    expect(suffix.accusative('retek')).toBe('retket')
    expect(suffix.accusative('szatyor')).toBe('szatyrot')
    expect(suffix.accusative('eper')).toBe('epret')
    expect(suffix.accusative('szitok')).toBe('szitkot')
    expect(suffix.accusative('titok')).toBe('titkot')
    expect(suffix.accusative('farok')).toBe('farkat')
  })
  it('exceptions tier 2', () => {
    expect(suffix.accusative('pohár')).toBe('poharat')
    expect(suffix.accusative('kanál')).toBe('kanalat')
    expect(suffix.accusative('kosár')).toBe('kosarat')
    expect(suffix.accusative('kenyér')).toBe('kenyeret')
    expect(suffix.accusative('levél')).toBe('levelet')
    expect(suffix.accusative('agár')).toBe('agarat')
    expect(suffix.accusative('tanár')).toBe('tanárt')
    expect(suffix.accusative('bogár')).toBe('bogarat')
  })
  it('exceptions tier 3', () => {
    expect(suffix.accusative('gabonapehely')).toBe('gabonapelyhet')
    expect(suffix.accusative('fagylaltkehely')).toBe('fagylaltkelyhet')
    expect(suffix.accusative('hely')).toBe('helyet')
  })
  it('exceptions tier 4', () => {
    expect(suffix.accusative('víz')).toBe('vizet')
    expect(suffix.accusative('tó')).toBe('tavat')
    expect(suffix.accusative('halastó')).toBe('halastavat')
    expect(suffix.accusative('Ottó')).toBe('Ottót')
    expect(suffix.accusative('hó')).toBe('havat')
    expect(suffix.accusative('fű')).toBe('füvet')
    expect(suffix.accusative('kő')).toBe('követ')
    expect(suffix.accusative('kút')).toBe('kutat')
  })
  it('exceptions tier 5', () => {
    expect(suffix.accusative('hal')).toBe('halat')
    expect(suffix.accusative('ház')).toBe('házat')
    expect(suffix.accusative('vár')).toBe('várat')
    expect(suffix.accusative('tej')).toBe('tejet')
    expect(suffix.accusative('fej')).toBe('fejet')
    expect(suffix.accusative('méz')).toBe('mézet')
  })
  it('exceptions tier 6', () => {
    expect(suffix.accusative('kéz')).toBe('kezet')
    expect(suffix.accusative('őz')).toBe('őzet')
    expect(suffix.accusative('vitéz')).toBe('vitézt')
  })
  it('exceptions tier 7', () => {
    expect(suffix.accusative('kefe')).toBe('kefét')
    expect(suffix.accusative('kapa')).toBe('kapát')
  })
  it('exceptions tier 8', () => {
    expect(suffix.accusative('szárny')).toBe('szárnyat')
    expect(suffix.accusative('szörny')).toBe('szörnyet')
    expect(suffix.accusative('abroncs')).toBe('abroncsot')
    expect(suffix.accusative('agancs')).toBe('agancsot')
    expect(suffix.accusative('kincs')).toBe('kincset')
    expect(suffix.accusative('bakancs')).toBe('bakancsot')
    expect(suffix.accusative('bilincs')).toBe('bilincset')
    expect(suffix.accusative('bogáncs')).toBe('bogáncsot')
    expect(suffix.accusative('kulcs')).toBe('kulcsot')
    expect(suffix.accusative('bölcs')).toBe('bölcset')
    expect(suffix.accusative('gyümölcs')).toBe('gyümölcsöt')
    expect(suffix.accusative('erkölcs')).toBe('erkölcsöt')
    expect(suffix.accusative('toll')).toBe('tollat')
    expect(suffix.accusative('szakáll')).toBe('szakállat')
    expect(suffix.accusative('sors')).toBe('sorsot')
    expect(suffix.accusative('gyors')).toBe('gyorsat')
    expect(suffix.accusative('bicepsz')).toBe('bicepszet')
    expect(suffix.accusative('gipsz')).toBe('gipszet')
    expect(suffix.accusative('mumpsz')).toBe('mumpszot')
    expect(suffix.accusative('birs')).toBe('birset')
    expect(suffix.accusative('boksz')).toBe('bokszot')
    expect(suffix.accusative('bors')).toBe('borsot')
    expect(suffix.accusative('borz')).toBe('borzot')
    expect(suffix.accusative('vers')).toBe('verset')
    expect(suffix.accusative('bridzs')).toBe('bridzset')
    expect(suffix.accusative('bronz')).toBe('bronzot')
    expect(suffix.accusative('pajzs')).toBe('pajzsot')
    expect(suffix.accusative('őrs')).toBe('őrsöt')
    expect(suffix.accusative('enyv')).toBe('enyvet')
    expect(suffix.accusative('törzs')).toBe('törzset')
    expect(suffix.accusative('torzs')).toBe('torzsot')
    expect(suffix.accusative('váll')).toBe('vállat')
    expect(suffix.accusative('gally')).toBe('gallyat')
    expect(suffix.accusative('genny')).toBe('gennyet')
    expect(suffix.accusative('orr')).toBe('orrot')
    expect(suffix.accusative('könny')).toBe('könnyet')
    expect(suffix.accusative('mell')).toBe('mellet')
    expect(suffix.accusative('menny')).toBe('mennyet')
    expect(suffix.accusative('sansz')).toBe('sanszot')
    expect(suffix.accusative('sánsz')).toBe('sánszot')
    expect(suffix.accusative('sánc')).toBe('sáncot')
    expect(suffix.accusative('szeánsz')).toBe('szeánszot')
    expect(suffix.accusative('szenny')).toBe('szennyet')
    expect(suffix.accusative('csimpánz')).toBe('csimpánzt')

    expect(suffix.accusative('rács')).toBe('rácsot')
    expect(suffix.accusative('abroncs')).toBe('abroncsot')
    expect(suffix.accusative('szárny')).toBe('szárnyat')
    expect(suffix.accusative('árny')).toBe('árnyat')
    expect(suffix.accusative('szörny')).toBe('szörnyet')
    expect(suffix.accusative('arany')).toBe('aranyat')
    expect(suffix.accusative('kulcs')).toBe('kulcsot')
    expect(suffix.accusative('apacs')).toBe('apacsot')
    expect(suffix.accusative('törzs')).toBe('törzset')
    expect(suffix.accusative('társ')).toBe('társat')
    expect(suffix.accusative('egész')).toBe('egészet')
    expect(suffix.accusative('szex')).toBe('szexet')
    expect(suffix.accusative('darázs')).toBe('darazsat')
    expect(suffix.accusative('delizsánsz')).toBe('delizsánszot')
    expect(suffix.accusative('toll')).toBe('tollat')
    expect(suffix.accusative('szakáll')).toBe('szakállat')
    expect(suffix.accusative('váladék')).toBe('váladékot')
    expect(suffix.accusative('szobor')).toBe('szobrot')
    expect(suffix.accusative('fédervejsz')).toBe('fédervejszet')
    expect(suffix.accusative('kapocs')).toBe('kapcsot')
    expect(suffix.accusative('tanács')).toBe('tanácsot')
    expect(suffix.accusative('parázs')).toBe('parazsat')
  })
})
