import { suffix } from '..'

describe('genitive case', () => {
  describe('simple cases', () => {
    it('should properly handle them', () => {
      expect(suffix.genitive('kar')).toBe('karja')
      expect(suffix.genitive('bagoly')).toBe('baglya')
      expect(suffix.genitive('fenék')).toBe('feneke')
      expect(suffix.genitive('kenyér')).toBe('kenyere')
      expect(suffix.genitive('fülemüle')).toBe('fülemüléje')
      expect(suffix.genitive('kosár')).toBe('kosara')
      expect(suffix.genitive('fiú')).toBe('fiúja')
      expect(suffix.genitive('farok')).toBe('farka')
      expect(suffix.genitive('fa')).toBe('fája')
      expect(suffix.genitive('frázis')).toBe('frázisa')
      expect(suffix.genitive('billentyűzet')).toBe('billentyűzete')
      expect(suffix.genitive('félelem')).toBe('félelme')
      expect(suffix.genitive('kurátor')).toBe('kurátora')
      expect(suffix.genitive('férj')).toBe('férje')
      expect(suffix.genitive('vádli')).toBe('vádlija')
      expect(suffix.genitive('mű')).toBe('műve')
      expect(suffix.genitive('teher')).toBe('terhe')
      expect(suffix.genitive('affér')).toBe('afférja')
      expect(suffix.genitive('frekvencia')).toBe('frekvenciája')
      expect(suffix.genitive('bér')).toBe('bére')
      expect(suffix.genitive('céh')).toBe('céhe')
      expect(suffix.genitive('tulipán')).toBe('tulipánja')
      expect(suffix.genitive('szén')).toBe('szene')
      expect(suffix.genitive('kürt')).toBe('kürtje')
      expect(suffix.genitive('kéz')).toBe('keze')
      expect(suffix.genitive('vő')).toBe('veje')
      expect(suffix.genitive('velő')).toBe('veleje')
    })
  })
})
